<a href="https://colab.research.google.com/github/Sanjar-prog/Telegram-JavaScript-Bot/blob/main/Pandas_Yakuniy_Amaliy_Vazifa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar!

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqlarni `📌Mavzulashtirdik`

## `📌Pandas kutubxonasini yuklash`

**1.** Pandas kutubxonasini `pd` nomi ostida yuklang va pandas kutubxonasini chop eting.

In [1]:
import pandas as pd

print(pd)


<module 'pandas' from '/usr/local/lib/python3.11/dist-packages/pandas/__init__.py'>


**2.** Versiya va konfiguratsiyani tekshiring.

In [2]:
print(pd.show_versions())  # Pandas va bog‘liq kutubxonalar haqida ma’lumot


/usr/local/lib/python3.11/dist-packages/_distutils_hack/__init__.py:31: UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(



INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.11.11.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.1.85+
Version               : #1 SMP PREEMPT_DYNAMIC Thu Jun 27 21:05:47 UTC 2024
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : en_US.UTF-8
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2025.1
dateutil              : 2.8.2
setuptools            : 75.1.0
pip                   : 24.1.2
Cython                : 3.0.12
pytest                : 8.3.4
hypothesis            : None
sphinx                : 8.1.3
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 5.3.1
html5lib              : 1.1
pymysql               : None
psycopg2   

**3.** Pandas kutubxonasida mavjud bo'lgan barcha versiya ma'lumotlarini chop eting.

In [3]:
import pandas as pd

pd.show_versions()



INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.11.11.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.1.85+
Version               : #1 SMP PREEMPT_DYNAMIC Thu Jun 27 21:05:47 UTC 2024
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : en_US.UTF-8
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 1.26.4
pytz                  : 2025.1
dateutil              : 2.8.2
setuptools            : 75.1.0
pip                   : 24.1.2
Cython                : 3.0.12
pytest                : 8.3.4
hypothesis            : None
sphinx                : 8.1.3
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 5.3.1
html5lib              : 1.1
pymysql               : None
psycopg2   

## `📌DataFrame: Asoslar`

DataFrames-da ma'lumotlarni tanlash(selecting), saralash(sorting), qo'shish(adding) va yig'ish(aggregating) uchun bir nechta asosiy mashqlar.

💡Eslatma: NumPy kutubxonasini import qilishni unutmang:
``` python
import numpy as np
```

Quyidagi Python lug'ati(dictionary) `data` va Python ro'yxati(list) `labels` ni ko'rib chiqing:


``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```



**4.** Ushbu `lug'at`(dictionary) yordamida `data` dan `labels` indeksiga ega DataFrame yarating.

In [4]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

# Natijani chop etish
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


**5.** Ushbu DataFrame va uning ma'lumotlari haqidagi asosiy ma'lumotlarning qisqacha mazmunini ko'rsating.

`💡Ishora:` DataFrame-da chaqirilishi mumkin bo'lgan yagona usul mavjud.

In [5]:
print(df.info())


<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes
None


**6.** DataFrame `df` dastlabki 3 qatorini qaytaring.

In [6]:
print(df.head(3))


  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no


**7.** DataFrame `df`-dan faqat `animal` va `age` ustunlarini tanlang.

In [7]:
print(df[['animal', 'age']])


  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0


**8.** `[3, 4, 8]` va `['animal', 'age']` qatorlaridagi ma'lumotlarni tanlang.

In [8]:
print(df.loc[df.index[[3, 4, 8]], ['animal', 'age']])


  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0


**9.** Faqat `visits` soni 3 tadan ko'p bo'lgan qatorlarni tanlang.

In [9]:
print(df.loc[df['visits'] > 3])


Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []


10. Yosh yo'qolgan qatorlarni tanlang, ya'ni `NaN`

In [10]:
print(df.loc[df['age'].isna()])


  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes


**11.** `animal` qatoridagi `cat` va `age` qatoridagi `3` dan kichik bo'lgan umumiy qatorlarni tanlang.

In [11]:
print(df.loc[(df['animal'] == 'cat') & (df['age'] < 3)])


  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no


**12.** `age` 2 va 4 (shu jumladan) orasidagi qatorlarni tanlang.

In [12]:
print(df.loc[(df['age'] >= 2) & (df['age'] <= 4)])


  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no


**13.** `f` qatoridagi yoshni `1,5` ga o'zgartiring.

In [13]:
df.loc['f', 'age'] = 1.5


**14.** `df` yordamida `visits` qatorining yig'indisini hisoblang.

In [14]:
total_visits = df['visits'].sum()
print(total_visits)


19


**15.** Har bir `animal` uchun o'rtacha yoshni `df` da hisoblang.

In [15]:
average_age_per_animal = df.groupby('animal')['age'].mean()
print(average_age_per_animal)


animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64


**16.** `df` yordamida har bir turdagi `animal` sonini hisoblang.

In [16]:
animal_count = df['animal'].value_counts()
print(animal_count)


animal
cat      4
dog      4
snake    2
Name: count, dtype: int64


**17.** `animal` ustunida, `snake` so'zini `python` so'ziga o'zgartiring.

In [17]:
df['animal'] = df['animal'].replace('snake', 'python')
print(df)


   animal  age  visits priority
a     cat  2.5       1      yes
b     cat  3.0       3      yes
c  python  0.5       2       no
d     dog  NaN       3      yes
e     dog  5.0       2       no
f     cat  1.5       3       no
g  python  4.5       1       no
h     cat  NaN       1      yes
i     dog  7.0       2       no
j     dog  3.0       1       no


## `📌DataFrame: Murakkab`

### Bir oz qiyinroq: to'g'ri javob olish uchun ikki yoki undan ortiq usullarni birlashtirish kerak bo'lishi mumkin

Oldingi bo'lim DataFrame-ning asosiy, ammo muhim operatsiyalari bo'yicha vazifalarni jamlagan edi. Quyida ma'lumotlarni kesishingiz kerak bo'lgan mashqlar mavjud.

**18.** Sizda butun sonlardan iborat `A` ustunli DataFrame `df` mavjud. Misol uchun:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

Yuqoridagi qator bilan bir xil butun sonni o'z ichiga olgan qator yarating.


💡Sizda quyidagi qiymatlarni o'z ichiga olgan ustun paydo bo'lishi kerak:

```python
1, 2, 3, 4, 5, 6, 7
```

**19.** Raqamli qiymatlardan iborat DataFrame berildi

```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # float qiymatlarining 5x3 o'lchovi
```

Qatordagi har bir elementdan satrning o'rtacha qiymatini qanday ayirish mumkin?

**20.** Sizda 10 ta haqiqiy raqamlar ustunidan iborat DataFrame mavjud:

``` python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
Qaysi sonlar ustunining yig'indisi eng kichik ekanini hisoblang. U ustunning yorlig'ini qaytaring.

**21.** Quyida butun sonlardan iborat DataFrame `df` mavjud. Har bir satrga  5 ta yozuv `NaN` qiymatlari kiritilgan.

DataFrame ning har bir qatori uchun uchinchi `NaN` qiymatini o'z ichiga olgan ustunni toping.

Ustun yorliqlarini qaytarishingiz kerak: `e, c, d, h, d`

In [19]:
nan = np.nan
data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)

# Javobni bu yerga yozing!
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
unique_values = df['A'].unique()
print(unique_values)


[1 2 3 4 5 6 7]


**22.** DataFrame `grps` guruhlari ustuniga va `vals` butun qiymatlari ustuniga ega:

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
Har bir `grps` uchun uchta eng katta qiymatning yig‘indisini toping.

💡Javobni quyidagicha yakunlashingiz kerak:
```
grps
a    409
b    156
c    345
```

     'a   a  a b  b  c a a  b  c  c   c  b  b  c'
      12,345,3,1,45,14,4,52,54,23,235,21,57,3,87

In [20]:
# Javobni bu yerga yozing!
import pandas as pd

df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12, 345, 3, 1, 45, 14, 4, 52, 54, 23, 235, 21, 57, 3, 87]})

# Har bir guruh uchun uchta eng katta qiymatni tanlash va yig'indi olish
result = df.groupby('grps')['vals'].nlargest(3).groupby('grps').sum()
print(result)


grps
a    409
b    156
c    345
Name: vals, dtype: int64


**23.** Quyida tuzilgan DataFrame `df` ikkita butun son ustuniga ega 'A' va 'B'. "A" dagi qiymatlar 1 dan 100 gacha (shu jumladan).

“A” dagi har bir 10 ta ketma-ket butun sonlar guruhi uchun (ya’ni `(0, 10]`, `(10, 20]`, ...) 'B' ustunidagi mos qiymatlar yig'indisini hisoblang.

Javob quyidagicha bo'lishi kerak:

```
A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
```

In [21]:
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])

# Javobni bu yerga yozing!

import pandas as pd
import numpy as np

# DataFrame yaratish
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns=["A", "B"])

# "A" ustuni bo'yicha intervallarni yaratish
bins = pd.cut(df['A'], bins=range(0, 110, 10))

# Har bir interval uchun "B" ustunining yig'indisini hisoblash
result = df.groupby(bins)['B'].sum()
print(result)


A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
Name: B, dtype: int64


<ipython-input-21-d145d294b7c0>:15: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  result = df.groupby(bins)['B'].sum()


**24.** 'X' butun son ustuni bo'lgan DataFrame:
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```

Har bir qiymat uchun farqni oldingi nolga qaytaring.

Sizda natija quyidagicha bo'lishi kerak:

```
[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
```

Buni yangi `Y` ustuni deb nomlang.

In [22]:
#javobni bu yerga yozing!
import pandas as pd

# DataFrame yaratish
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})

# X ustuni bo'yicha farqni oldingi nolga qaytarish
df['Y'] = df['X'].where(df['X'] != 0).cumsum() - df['X'].where(df['X'] == 0).cumsum()

print(df['Y'].tolist())


[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]


##`📌Ma'lumotlarni tozalash`

Bu har doim sodir bo'ladi: kimdir sizga noto'g'ri tuzilgan satrlar, ro'yxatlar va yetishmayotgan ma'lumotlarni o'z ichiga olgan ma'lumotlarni beradi. Tahlilni davom ettirish uchun uni qanday tartibga keltirasiz?

**25.** Quyidagi jumboqni tasavvur qilishi uchun ushbu misolni DataFrame sifatida oling:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
```
Tartiblaganingizdan so'ng u quyidagi ko'rinishga ega bo'lishi kerak:

```
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
```


In [23]:
import pandas as pd
import numpy as np

# DataFrame yaratish
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
                   'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
                   'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})

# 1. 'From_To' ustunidagi qiymatlarni to'g'ri formatlash (barcha harflarni kichik qilish va qismlarini ajratish)
df['From_To'] = df['From_To'].str.title().str.replace('_', ' ')

# 2. 'FlightNumber' ustunidagi NaN qiymatlarni yaxshilash (ularni saqlash)
df['FlightNumber'] = df['FlightNumber'].fillna(method='ffill')  # Oldingi qiymatni ko'chirib kelish

# 3. 'Airline' ustunidagi noodatiy belgilarni tozalash (maxsus belgilarni olib tashlash)
df['Airline'] = df['Airline'].str.replace('[^A-Za-z0-9 ]', '', regex=True)

# 4. Barcha ustunlar formatlarini tekshirish
print(df)


            From_To  FlightNumber  RecentDelays           Airline
0      London Paris       10045.0      [23, 47]               KLM
1      Madrid Milan       10045.0            []     Air France 12
2  London Stockholm       10065.0  [24, 43, 87]  British Airways 
3    Budapest Paris       10065.0          [13]     12 Air France
4   Brussels London       10085.0      [67, 32]         Swiss Air


<ipython-input-23-9ae915ed1e71>:16: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['FlightNumber'] = df['FlightNumber'].fillna(method='ffill')  # Oldingi qiymatni ko'chirib kelish


**26.** **FlightNumber** ustunidagi ba'zi qiymatlar yo'q. Ular `NaN` ko'rinishida yozilgan. Bu raqamlar har bir qatorda 10 ga ko'payishi kerak, shuning uchun 10055 va 10075 ni qo'yish kerak. Ushbu yetishmayotgan raqamlarni to'ldirish uchun `df` ni o'zgartiring va ustunni butun son ustuniga aylantiring.

In [24]:
import pandas as pd
import numpy as np

# DataFrame yaratish
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
                   'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
                   'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})

# FlightNumber ustunidagi NaN qiymatlarni 10 ga ko'paytirish
df['FlightNumber'] = df['FlightNumber'].fillna(method='ffill') + 10  # NaN qiymatlarni oldingi qiymatga 10 qo'shish

# FlightNumber ustunini butun son turiga o'zgartirish
df['FlightNumber'] = df['FlightNumber'].astype(int)

# Natijani ko'rsatish
print(df)


            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10055      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10075  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10095      [67, 32]          "Swiss Air"


<ipython-input-24-ea944eeb2e15>:13: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['FlightNumber'] = df['FlightNumber'].fillna(method='ffill') + 10  # NaN qiymatlarni oldingi qiymatga 10 qo'shish


**27.** **From\_To** ustunini ikkita alohida ustun ko'rinishida yozing.                                          

To'g'ri qiymatlarga ega `temp` deb nomlangan yangi Temporary DataFrame berish uchun har bir satrni pastki chiziq chegarasiga ajrating.                                                                     Ushbu Temporary DataFrame ustunlarini `From` va `To` deb nomlang.

In [25]:
import pandas as pd
import numpy as np

# DataFrame yaratish
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
                   'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
                   'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})

# From_To ustunini ajratish
temp = df['From_To'].str.split('_', expand=True)  # pastki chiziq bo'yicha ajratish

# Yangi ustunlarni nomlash
temp.columns = ['From', 'To']

# Asl DataFrame bilan qo'shish
df = df.join(temp)

# Natijani ko'rsatish
print(df)


            From_To  FlightNumber  RecentDelays              Airline  \
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)   
1      MAdrid_miLAN           NaN            []    <Air France> (12)   
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )   
3    Budapest_PaRis           NaN          [13]       12. Air France   
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"   

       From         To  
0    LoNDon      paris  
1    MAdrid      miLAN  
2    londON  StockhOlm  
3  Budapest      PaRis  
4  Brussels     londOn  


**28.** Temporary DataFrame `temp` da shahar nomlari betartib yozilgan.Satrlarning faqat birinchi harfi katta yozilishi kerak.
                                                                         (Masalan, "londON" "London" bo'lishi kerak.)

In [26]:
import pandas as pd
import numpy as np

# DataFrame yaratish
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
                   'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
                   'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})

# From_To ustunini ajratish
temp = df['From_To'].str.split('_', expand=True)  # pastki chiziq bo'yicha ajratish

# Yangi ustunlarni nomlash
temp.columns = ['From', 'To']

# Shahar nomlarini to'g'ri formatlash
temp['From'] = temp['From'].str.capitalize()  # "From" ustunidagi shaharlarni formatlash
temp['To'] = temp['To'].str.capitalize()      # "To" ustunidagi shaharlarni formatlash

# Asl DataFrame bilan qo'shish
df = df.join(temp)

# Natijani ko'rsatish
print(df)


            From_To  FlightNumber  RecentDelays              Airline  \
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)   
1      MAdrid_miLAN           NaN            []    <Air France> (12)   
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )   
3    Budapest_PaRis           NaN          [13]       12. Air France   
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"   

       From         To  
0    London      Paris  
1    Madrid      Milan  
2    London  Stockholm  
3  Budapest      Paris  
4  Brussels     London  


**29**. `Airline` ustunida aviakompaniya nomlari atrofida qoʻshimcha tinish belgilari va belgilar paydo boʻlganini koʻrishingiz mumkin. Faqat aviakompaniya nomini qoldiring. Masalan, ʻ'(British Airways. )'' `British Airways` ko'rinishida yozilishi kerak.

In [27]:
import pandas as pd
import numpy as np

# DataFrame yaratish
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
                   'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
                   'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})

# Airline ustunidagi tinish belgilari va belgilarni olib tashlash
df['Airline'] = df['Airline'].str.replace(r'[^\w\s]', '', regex=True)

# Natijani ko'rsatish
print(df)


            From_To  FlightNumber  RecentDelays           Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM
1      MAdrid_miLAN           NaN            []     Air France 12
2  londON_StockhOlm       10065.0  [24, 43, 87]  British Airways 
3    Budapest_PaRis           NaN          [13]     12 Air France
4   Brussels_londOn       10085.0      [67, 32]         Swiss Air


**30.** `df` dan **From_To** ustunini o'chiring va Temporary DataFrame `temp` ustunini qo'shing.

In [34]:
# From_To' ustunini o'chirish
# Check if 'From_To' column exists before dropping
if 'From_To' in df.columns:
  df = df.drop(columns=['From_To'])
else:
  print("Column 'From_To' not found in DataFrame")

# 'temp' ustunidagi 'From' va 'To' ustunlarini df ga qo'shish
df['From'] = temp['From']  # 'From' ustunini df ga qo'shish
df['To'] = temp['To']    # 'To' ustunini df ga qo'shish

# Natijani ko'rsatish
print(df)

Column 'From_To' not found in DataFrame
   FlightNumber  RecentDelays           Airline      From         To
0       10045.0      [23, 47]               KLM    London      Paris
1           NaN            []     Air France 12    Madrid      Milan
2       10065.0  [24, 43, 87]  British Airways     London  Stockholm
3           NaN          [13]     12 Air France  Budapest      Paris
4       10085.0      [67, 32]         Swiss Air  Brussels     London


**31**. `RecentDelays` ustunida qiymatlar DataFrame-ga ro'yxat sifatida kiritilgan. Sizning vazifangiz birinchi qiymatni o'z ustunida, har bir ikkinchi qiymatni o'z ustunida va qolgan qiymatlar ham ustunga mos holda chop etish. Agar N-chi qiymat bo'lmasa, qiymat `NaN` deb nomlanishi kerak.

Roʻyxatlar qatorini `delays` nomli DataFrame ichiga kengaytiring, `delay_1`, `delay_2` va qolgan ustunlarni ham nomlarini oʻzgartiring va `df` dagi keraksiz `RecentDelays` ustunini `delays` bilan almashtiring.

Natija quyidagi ko'rinishda bo'lishi kerak:
```
   FlightNumber          Airline      From         To  delay_1  delay_2  delay_3
0         10045              KLM    London      Paris     23.0     47.0      NaN
1         10055       Air France    Madrid      Milan      NaN      NaN      NaN
2         10065  British Airways    London  Stockholm     24.0     43.0     87.0
3         10075       Air France  Budapest      Paris     13.0      NaN      NaN
4         10085        Swiss Air  Brussels     London     67.0     32.0      NaN
```

In [35]:
# RecentDelays ustunini kengaytirish
delays = df['RecentDelays'].apply(pd.Series)

# Ustun nomlarini delay_1, delay_2, delay_3... deb o'zgartirish
delays.columns = [f'delay_{i+1}' for i in range(delays.shape[1])]

# df ga delays ustunlarini qo'shish
df = df.drop(columns=['RecentDelays']).join(delays)

# Natijani ko'rsatish
print(df)


   FlightNumber           Airline      From         To  delay_1  delay_2  \
0       10045.0               KLM    London      Paris     23.0     47.0   
1           NaN     Air France 12    Madrid      Milan      NaN      NaN   
2       10065.0  British Airways     London  Stockholm     24.0     43.0   
3           NaN     12 Air France  Budapest      Paris     13.0      NaN   
4       10085.0         Swiss Air  Brussels     London     67.0     32.0   

   delay_3  
0      NaN  
1      NaN  
2     87.0  
3      NaN  
4      NaN  


##`📌Minesweeper`


### Minesweeper tarmog'ida xavfsiz kvadratlar uchun raqamlar yaratamiz!

💡 Agar siz Windowsning avvalgi versiyalaridan foydalangan bo'lsangiz, Minesweeper bilan tanishsiz:
- https://en.wikipedia.org/wiki/Minesweeper_(video_game)

Agar siz o'yin bilan tanish bo'lmasangiz, kvadratchalar to'plamini tasavvur qiling: bu kvadratlarning ba'zilari mineni yashiradi. Agar siz mineni bossangiz, darhol yo'qotasiz. Agar siz xavfsiz kvadratni bossangiz, darhol qo'shni bo'lgan kvadratchalarda qancha mine borligini ko'rsatadigan raqamni ko'rasiz. O'yinning maqsadi to'rdagi mine bo'lmagan barcha kvadratlarni ochishdir.

Ushbu bo'limda biz Minesweeper o'yini uchun kerakli ma'lumotlarni o'z ichiga olgan DataFrame yaratamiz: kvadratlarning koordinatalari, kvadratda mine bormi va qo'shni kvadratlarda topilgan minelar sonini aniqlaymiz!

**32**. Tasavvur qiling, biz Minesweeper o'yinini 5 dan 4 gacha bo'lgan panjarada o'ynayapmiz, ya'ni.
```
X = 5
Y = 4
```
Boshlash uchun ikkita ustunli DataFrame `df` yarating, bu tarmoq uchun har bir koordinatani o'z ichiga olgan `'x'` va `'y'`. Ya'ni DataFrame ishga tushishi kerak:
```
    x y
0 0 0
1 0 1
2 0 2
```

In [36]:
import pandas as pd

# Tarmoq o'lchamlari
X = 5  # Ustunlar soni
Y = 4  # Qatorlar soni

# Har bir kvadratning koordinatalarini yaratish
coordinates = [(x, y) for x in range(X) for y in range(Y)]

# DataFrame yaratish
df = pd.DataFrame(coordinates, columns=['x', 'y'])

# Natijani ko'rsatish
print(df)


    x  y
0   0  0
1   0  1
2   0  2
3   0  3
4   1  0
5   1  1
6   1  2
7   1  3
8   2  0
9   2  1
10  2  2
11  2  3
12  3  0
13  3  1
14  3  2
15  3  3
16  4  0
17  4  1
18  4  2
19  4  3


**33**. Ushbu DataFrame `df` uchun yangi nol (safe) va birliklar (mine) ustunini yarating. Har bir joyda mine sodir bo'lish ehtimoli 0,4 bo'lishi kerak.

In [37]:
import pandas as pd
import numpy as np

# Tarmoq o'lchamlari
X = 5  # Ustunlar soni
Y = 4  # Qatorlar soni

# Har bir kvadratning koordinatalarini yaratish
coordinates = [(x, y) for x in range(X) for y in range(Y)]

# DataFrame yaratish
df = pd.DataFrame(coordinates, columns=['x', 'y'])

# Mine bo'lish ehtimoli
mine_probability = 0.4

# Tasodifiy mine (1) va safe (0) qiymatlarini yaratish
df['mine'] = np.random.choice([0, 1], size=len(df), p=[1 - mine_probability, mine_probability])

# Natijani ko'rsatish
print(df)


    x  y  mine
0   0  0     1
1   0  1     0
2   0  2     1
3   0  3     1
4   1  0     0
5   1  1     1
6   1  2     1
7   1  3     0
8   2  0     0
9   2  1     1
10  2  2     1
11  2  3     1
12  3  0     0
13  3  1     0
14  3  2     0
15  3  3     0
16  4  0     0
17  4  1     0
18  4  2     0
19  4  3     1


 **34**. Endi ushbu DataFrame uchun `adjacent` nomli yangi ustun yarating. Ushbu ustunda tarmoqdagi qo'shni kvadratlarda topilgan minelar soni bo'lishi kerak.

(Masalan, `(0, 0)` koordinatasi uchun yozuv bo'lgan birinchi qator uchun `(0, 1)`, `(1, 0)` va `(1) koordinatalarida qancha mine borligini hisoblang. , 1)`.)

In [38]:
import pandas as pd
import numpy as np

# Tarmoq o'lchamlari
X = 5  # Ustunlar soni
Y = 4  # Qatorlar soni

# Har bir kvadratning koordinatalarini yaratish
coordinates = [(x, y) for x in range(X) for y in range(Y)]

# DataFrame yaratish
df = pd.DataFrame(coordinates, columns=['x', 'y'])

# Mine bo'lish ehtimoli
mine_probability = 0.4

# Tasodifiy mine (1) va safe (0) qiymatlarini yaratish
df['mine'] = np.random.choice([0, 1], size=len(df), p=[1 - mine_probability, mine_probability])

# Qo'shni kvadratlarni hisoblash
def count_adjacent_mines(x, y):
    # Qo'shni kvadratlarning koordinatalari (yuqoridagi, pastdagi, chapdagi, o'ngdagi)
    neighbors = [
        (x-1, y-1), (x-1, y), (x-1, y+1),  # yuqoridagi 3 kvadrat
        (x, y-1), (x, y+1),                 # chap va o'ngdagi kvadratlar
        (x+1, y-1), (x+1, y), (x+1, y+1)   # pastdagi 3 kvadrat
    ]

    # Qo'shni kvadratlarda minelarni hisoblash
    count = 0
    for nx, ny in neighbors:
        if 0 <= nx < X and 0 <= ny < Y:  # Koordinatlar to'g'ri chegarada bo'lsa
            count += df.loc[(df['x'] == nx) & (df['y'] == ny), 'mine'].values[0]
    return count

# Har bir kvadrat uchun qo'shni minelar sonini hisoblab 'adjacent' ustunini yaratish
df['adjacent'] = df.apply(lambda row: count_adjacent_mines(row['x'], row['y']), axis=1)

# Natijani ko'rsatish
print(df)


    x  y  mine  adjacent
0   0  0     0         0
1   0  1     0         1
2   0  2     0         1
3   0  3     0         1
4   1  0     0         0
5   1  1     0         2
6   1  2     1         1
7   1  3     0         2
8   2  0     0         1
9   2  1     0         3
10  2  2     1         2
11  2  3     0         3
12  3  0     1         0
13  3  1     0         3
14  3  2     0         4
15  3  3     1         3
16  4  0     0         1
17  4  1     0         2
18  4  2     1         2
19  4  3     1         2


**35**. Mineni o'z ichiga olgan DataFrame qatorlari uchun `adjacent` ustunidagi qiymatni `NaN` ga o'zgartiring.

In [39]:
# Mineni o'z ichiga olgan qatorlar uchun 'adjacent' ustunini NaN ga o'zgartirish
df.loc[df['mine'] == 1, 'adjacent'] = np.nan

# Natijani ko'rsatish
print(df)


    x  y  mine  adjacent
0   0  0     0       0.0
1   0  1     0       1.0
2   0  2     0       1.0
3   0  3     0       1.0
4   1  0     0       0.0
5   1  1     0       2.0
6   1  2     1       NaN
7   1  3     0       2.0
8   2  0     0       1.0
9   2  1     0       3.0
10  2  2     1       NaN
11  2  3     0       3.0
12  3  0     1       NaN
13  3  1     0       3.0
14  3  2     0       4.0
15  3  3     1       NaN
16  4  0     0       1.0
17  4  1     0       2.0
18  4  2     1       NaN
19  4  3     1       NaN


**36**. DataFrame-ni `adjacent` minelar sonining panjarasiga aylantiring: ustunlar `x` koordinatasi, qatorlar `y` koordinatasi.

In [40]:
# DataFrame-ni 'x' va 'y' ustunlaridan foydalangan holda panjara shaklida qayta tashkil qilish
pivot_df = df.pivot(index='y', columns='x', values='adjacent')

# Natijani ko'rsatish
print(pivot_df)


x    0    1    2    3    4
y                         
0  0.0  0.0  1.0  NaN  1.0
1  1.0  2.0  3.0  3.0  2.0
2  1.0  NaN  NaN  4.0  NaN
3  1.0  2.0  3.0  NaN  NaN


##📌BONUS!

O'zingiz javob berishni istagan savolni kiriting va unga javob bering!

## Pandas DataFrame'ini qanday qilib ma'lum bir ustun bo'yicha saralash mumkin?

In [41]:
import pandas as pd

# DataFrame yaratish
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Score': [85, 92, 78, 88]
})

# 'Age' ustuni bo'yicha saralash
df_sorted = df.sort_values(by='Age')

# Natijani ko'rsatish
print(df_sorted)


      Name  Age  Score
0    Alice   25     85
1      Bob   30     92
2  Charlie   35     78
3    David   40     88
